### PR TITLE
fix: dont report DAP037 on array types

### LINKED ISSUE #123: DAP037 error when return type is an array
Hello,

for ExecuteScalar and QuerySingleOrDefault methods DAP037 error is reported ("No settable members exist for user type"), when return type is an array like `byte[]` or `string[]`. 

``` C#
public async Task<byte[]?> TryGetByteArray(NpgsqlConnection conn, long id)
{
    var bytes = await conn.ExecuteScalarAsync<byte[]>(
        "select blob from foo where id = @id",
        param: new { id });
    return bytes;
}
```

Expected behavior: No error.

- Dapper v2.1.35
- Dapper.AOT v1.0.31
- Npgsql v8.0.3

### PR DESCRIPTION
**Pull request by DeagleGross**
I believe this is a correct usage of where result type is either `userType[]` or `primitiveType[]`.
```
await conn.Query<byte[]>(...)
```
We should not report the [DAP037](https://github.com/DapperLib/DapperAOT/blob/main/docs/rules/DAP037.md), because lets say `byte[]` does not have accessible fields\properties, but it is valid expected result type.

Closes #123

### CODE REVIEW

**Comment by mgravell** [comment]
I don't think we want to unwrap *every* array type - semantically I'm not sure what `string[]`, `int[]` etc mean, so we shouldn't IMO pretend to understand them. Instead, I think we should recognize *explicitly and only* `byte[]` (and possibly `sbyte[]`, although I don't think Dapper vanilla supports the latter), to interpret as BLOB data.

**Review by mgravell — APPROVED** [review]

**Comment by mgravell** [comment]
Nice, thanks

**Comment by Jure-BB** [comment]
> I don't think we want to unwrap every array type - semantically I'm not sure what `string[]`, `int[]` etc mean, so we shouldn't IMO pretend to understand them. Instead, I think we should recognize _explicitly and only_ `byte[]` (and possibly `sbyte[]`, although I don't think Dapper vanilla supports the latter), to interpret as BLOB data.

@mgravell PostgreSQL columns [support arrays](https://www.postgresql.org/docs/current/arrays.html) of different types. Npgsql [maps array types](https://www.npgsql.org/doc/types/basic.html#read-mappings) to `Array (of element type)`. 

For example:
``` sql
create table arrays_table
(
    id int4  not null unique,
    strings  text[],
    ints     int4[]
);

insert into arrays_table (id, strings, ints) values
(1, array['a', 'b', 'c'], array[1, 2, 3]),
(2, array['d', 'e', 'f'], array[4, 5, 6]),
(3, array['g', 'h', 'i'], array[7, 8, 9]);
```

With Dapper vanilla an array column can be selected as 
`IEnumerable<string[]> result = await conn.Query<string[]>("select strings from arrays_table")` 
or `string[]? strings = conn.QuerySingleOrDefault<string[]>("select strings from arrays_table where id = 1")`, 
but with DapperAOT these fail to compile.

**Comment by mgravell** [comment]
@Jure-BB fair enough; in all these things, the key is finding these examples so we can prove them; did you want to log a new issue for that?

**Comment by Jure-BB** [comment]
@mgravell #123 was intended for that, but I should have clarified the issue better. Would it be better if I edit the original issue or open a new one?

**Comment by mgravell** [comment]
Ah, `byte[]` is inherently a different case, because a much wider range of databases support BLOBs. Probably a new issue would be great.

**Comment by Jure-BB** [comment]
I've created #156 issue for arrays of other types.

**Pull request merged**
